create table if not exists  boleto_retorno  (
   id SERIAL PRIMARY KEY,
   idboleto INT,
   codigo_linha_digitavel VARCHAR,
   texto_email_pagador VARCHAR,
   texto_mensagem_bloqueto_titulo VARCHAR,
   codigo_canal_pagamento INT,
   numero_contrato_cobranca INT,
   codigo_prefixo_dependencia_cobrador INT,
   codigo_indicador_economico INT,
   data_registro_titulo_cobranca TIMESTAMP,
   valor_atual_titulo_cobranca FLOAT,
   valor_pagamento_parcial_titulo FLOAT,
   percentual_imposto_sobre_opr_financeiras_titulo_cobranca FLOAT,
   valor_imposto_sobre_opr_financeiras_titulo_cobranca FLOAT,
   valor_moeda_titulo_cobranca FLOAT,
   quantidade_parcela_titulo_cobranca INT,
   data_baixa_automatico_titulo TIMESTAMP,
   indicador_cobranca_partilhado_titulo VARCHAR,
   valor_moeda_abatimento_titulo FLOAT,
   data_protesto_titulo_cobranca TIMESTAMP,
   codigo_tipo_inscricao_sacador INT,
   numero_inscricao_sacador_avalista VARCHAR,
   nome_sacador_avalista_titulo VARCHAR,
   percentual_segundo_desconto_titulo FLOAT,
   data_segundo_desconto_titulo VARCHAR,
   valor_segundo_desconto_titulo FLOAT,
   codigo_segundo_desconto_titulo INT,
   percentual_terceiro_desconto_titulo FLOAT,
   data_terceiro_desconto_titulo TIMESTAMP,
   valor_terceiro_desconto_titulo FLOAT,
   codigo_terceiro_desconto_titulo INT,
   quantidade_dia_prazo_limite_recebimento INT,
   data_limite_recebimento_titulo TIMESTAMP,
   texto_codigo_barras_titulo_cobranca VARCHAR,
   codigo_ocorrencia_cartorio INT,
   valor_imposto_sobre_opr_financeiras_recebido_titulo FLOAT,
   valor_abatimento_total FLOAT,
   valor_juro_mora_recebido FLOAT,
   valor_desconto_utilizado FLOAT,
   valor_pago_sacado FLOAT,
   valor_credito_cedente FLOAT,
   codigo_tipo_liquidacao  INT,
   data_recebimento_titulo TIMESTAMP,
   codigo_prefixo_dependencia_recebedor INT,
   codigo_natureza_recebimento INT,
   numero_identidade_sacado_titulo_cobranca VARCHAR,
   codigo_responsavel_atualizacao VARCHAR,
   codigo_tipo_baixa_titulo INT,
   valor_multa_recebido FLOAT,
   valor_reajuste FLOAT,
   valor_outro_recebido FLOAT,
   codigo_indicador_economico_utilizado_inadimplencia INT,

   FOREIGN KEY (idboleto) REFERENCES boletos (id)
);
