CREATE TABLE boletos_status_final (
	id int4 NOT NULL,
	conta_id int4 NULL,
	nossonumero int4 NULL,
	numero_convenio int4 NULL,
	numero_carteira int4 NULL,
	numero_variacao_carteira int4 NULL,
	codigo_modalidade int4 NULL,
	valor_original float8 NULL,
	valor_abatimento float8 NULL,
	quantidade_dias_protesto int4 NULL,
	quantidade_dias_negativacao int4 NULL,
	orgao_negativador int4 NULL,
	indicador_aceite_titulo_vencido varchar(100) NULL,
	numero_dias_limite_recebimento int4 NULL,
	codigo_aceite varchar(100) NULL,
	codigo_tipo_titulo int4 NULL,
	descricao_tipo_titulo varchar(100) NULL,
	indicador_permissao_recebimento_parcial varchar(100) NULL,
	numero_titulo_beneficiario int4 NULL,
	campo_utilizacao_beneficiario varchar(100) NULL,
	numero_titulo_cliente varchar(100) NULL,
	mensagem_bloqueto_ocorrencia varchar(100) NULL,
	indicador_pix varchar(100) NULL,
	status int4 NULL,
	desconto_id int4 NULL,
	segundo_desconto_id int4 NULL,
	terceiro_desconto_id int4 NULL,
	juros_mora_id int4 NULL,
	multa_id int4 NULL,
	pagador_id int4 NULL,
	beneficiario_final_id int4 NULL,
	codigo_estado_titulo_cobranca int4 NULL,
	indicador_nova_data_vencimento varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_atribuir_desconto varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_alterar_desconto varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_alterar_data_desconto varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_protestar varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_sustacao_protesto varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_cancelar_protesto varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_incluir_abatimento varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_cancelar_abatimento varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_cobrar_juros varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_dispensar_juros varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_cobrar_multa varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_dispensar_multa varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_negativar varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_alterar_nosso_numero varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_alterar_endereco_pagador varchar(2) NULL DEFAULT 'N'::character varying,
	indicador_alterar_prazo_boleto_vencido varchar(2) NULL DEFAULT 'N'::character varying,
	tipo_negativacao int4 NULL,
	quantidade_dias_aceite int4 NULL,
	data_registro varchar(100) NULL,
	estado_titulo_cobranca varchar(100) NULL,
	contrato int4 NULL,
	data_movimento varchar(100) NULL,
	data_credito varchar(100) NULL,
	valor_atual float8 NULL,
	valor_pago float8 NULL,
	url varchar NULL,
	tx_id varchar NULL,
	emv varchar NULL,
	data_emissao timestamp NULL,
	data_vencimento timestamp NULL,
	cod_linha_digitavel varchar(50) NULL,
	dh_credito_liquidacao timestamp NULL,
	dh_recebimento_titulo timestamp NULL,
	dh_created_at timestamp NULL,
	dh_updated_at timestamp NULL,
	status_banco int4 NULL,
	nro_documento varchar(15) NULL,
	quantidade_tentativas int4 NULL DEFAULT 0,
	valor_juro_mora_recebido float8 NULL,
	valor_multa_recebido float8 NULL,
	data_registro_banco timestamp NULL,
	is_api bool NULL DEFAULT false,
	indicador_alterar_valor_original varchar(2) NULL DEFAULT 'N'::character varying,
	instrucao_protesto int4 NULL,
	instrucao_negativacao int4 NULL,
	contabilizar_dias bool NOT NULL DEFAULT true,
	CONSTRAINT boletosStatusFinal_pkey PRIMARY KEY (id)
);

ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_beneficiario_final_id_fkey FOREIGN KEY (beneficiario_final_id) REFERENCES public.beneficiariofinal(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_conta_id_fkey FOREIGN KEY (conta_id) REFERENCES public.contas(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_desconto_id_fkey FOREIGN KEY (desconto_id) REFERENCES public.desconto(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_juros_mora_id_fkey FOREIGN KEY (juros_mora_id) REFERENCES public.jurosmora(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_multa_id_fkey FOREIGN KEY (multa_id) REFERENCES public.multa(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_pagador_id_fkey FOREIGN KEY (pagador_id) REFERENCES public.pagador(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_segundo_desconto_id_fkey FOREIGN KEY (segundo_desconto_id) REFERENCES public.desconto(id);
ALTER TABLE boletos_status_final ADD CONSTRAINT boletos_status_final_terceiro_desconto_id_fkey FOREIGN KEY (terceiro_desconto_id) REFERENCES public.desconto(id);

ALTER TABLE boleto_retorno DROP CONSTRAINT boleto_retorno_idboleto_fkey;