insert into bancos (id, nome, ativo) values (70	,'BRB - BANCO DE BRASILIA S.A.', false);
insert into bancos (id, nome, ativo) values (430	,'COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA', false);
insert into bancos (id, nome, ativo) values (272	,'AGK CORRETORA DE CAMBIO S.A.', false);
insert into bancos (id, nome, ativo) values (136	,'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI', false);
insert into bancos (id, nome, ativo) values (407	,'ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (104	,'CAIXA ECONOMICA FEDERAL', false);
insert into bancos (id, nome, ativo) values (77	,'Banco Inter S.A.', false);
insert into bancos (id, nome, ativo) values (423	,'COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS', false);
insert into bancos (id, nome, ativo) values (741	,'BANCO RIBEIRAO PRETO S.A.', false);
insert into bancos (id, nome, ativo) values (330	,'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.', false);
insert into bancos (id, nome, ativo) values (739	,'Banco Cetelem S.A.', false);
insert into bancos (id, nome, ativo) values (743	,'Banco Semear S.A.', false);
insert into bancos (id, nome, ativo) values (100	,'Planner Corretora de Valores S.A.', false);
insert into bancos (id, nome, ativo) values (541	,'FUNDO GARANTIDOR DE CREDITOS - FGC', false);
insert into bancos (id, nome, ativo) values (96	,'Banco B3 S.A.', false);
insert into bancos (id, nome, ativo) values (747	,'Banco Rabobank International Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (362	,'CIELO S.A. - INSTITUIÇÃO DE PAGAMENTO', false);
insert into bancos (id, nome, ativo) values (322	,'Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz', false);
insert into bancos (id, nome, ativo) values (748	,'BANCO COOPERATIVO SICREDI S.A.', false);
insert into bancos (id, nome, ativo) values (350	,'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE', false);
insert into bancos (id, nome, ativo) values (752	,'Banco BNP Paribas Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (379	,'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS DE INSTITU', false);
insert into bancos (id, nome, ativo) values (399	,'Kirton Bank S.A. - Banco Múltiplo', false);
insert into bancos (id, nome, ativo) values (378	,'BANCO BRASILEIRO DE CRÉDITO SOCIEDADE ANÔNIMA', false);
insert into bancos (id, nome, ativo) values (413	,'BANCO BV S.A.', false);
insert into bancos (id, nome, ativo) values (756	,'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB', false);
insert into bancos (id, nome, ativo) values (360	,'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (757	,'BANCO KEB HANA DO BRASIL S.A.', false);
insert into bancos (id, nome, ativo) values (102	,'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A', false);
insert into bancos (id, nome, ativo) values (84	,'UNIPRIME DO BRASIL - COOPERATIVA DE CRÉDITO', false);
insert into bancos (id, nome, ativo) values (180	,'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (66	,'BANCO MORGAN STANLEY S.A.', false);
insert into bancos (id, nome, ativo) values (15	,'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (143	,'Treviso Corretora de Câmbio S.A.', false);
insert into bancos (id, nome, ativo) values (62	,'Hipercard Banco Múltiplo S.A.', false);
insert into bancos (id, nome, ativo) values (74	,'Banco J. Safra S.A.', false);
insert into bancos (id, nome, ativo) values (99	,'UNIPRIME CENTRAL NACIONAL - CENTRAL NACIONAL DE COOPERATIVA DE CREDITO', false);
insert into bancos (id, nome, ativo) values (387	,'Banco Toyota do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (326	,'PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (25	,'Banco Alfa S.A.', false);
insert into bancos (id, nome, ativo) values (75	,'Banco ABN Amro S.A.', false);
insert into bancos (id, nome, ativo) values (40	,'Banco Cargill S.A.', false);
insert into bancos (id, nome, ativo) values (307	,'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.', false);
insert into bancos (id, nome, ativo) values (385	,'COOPERATIVA DE ECONOMIA E CREDITO MUTUO DOS TRABALHADORES PORTUARIOS DA GRANDE V', false);
insert into bancos (id, nome, ativo) values (425	,'SOCINAL S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (190	,'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS E MUNICIPAI', false);
insert into bancos (id, nome, ativo) values (296	,'OZ CORRETORA DE CÂMBIO S.A.', false);
insert into bancos (id, nome, ativo) values (63	,'Banco Bradescard S.A.', false);
insert into bancos (id, nome, ativo) values (191	,'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.', false);
insert into bancos (id, nome, ativo) values (382	,'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L', false);
insert into bancos (id, nome, ativo) values (64	,'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.', false);
insert into bancos (id, nome, ativo) values (459	,'COOPERATIVA DE CRÉDITO MÚTUO DE SERVIDORES PÚBLICOS DO ESTADO DE SÃO PAULO - CRE', false);
insert into bancos (id, nome, ativo) values (97	,'Credisis - Central de Cooperativas de Crédito Ltda.', false);
insert into bancos (id, nome, ativo) values (16	,'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI', false);
insert into bancos (id, nome, ativo) values (299	,'BANCO AFINZ S.A. - BANCO MÚLTIPLO', false);
insert into bancos (id, nome, ativo) values (471	,'COOPERATIVA DE ECONOMIA E CREDITO MUTUO DOS SERVIDORES PUBLICOS DE PINHÃO - CRES', false);
insert into bancos (id, nome, ativo) values (468	,'PORTOSEG S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (12	,'Banco Inbursa S.A.', false);
insert into bancos (id, nome, ativo) values (3	,'BANCO DA AMAZONIA S.A.', false);
insert into bancos (id, nome, ativo) values (60	,'Confidence Corretora de Câmbio S.A.', false);
insert into bancos (id, nome, ativo) values (37	,'Banco do Estado do Pará S.A.', false);
insert into bancos (id, nome, ativo) values (411	,'Via Certa Financiadora S.A. - Crédito, Financiamento e Investimentos', false);
insert into bancos (id, nome, ativo) values (359	,'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A', false);
insert into bancos (id, nome, ativo) values (159	,'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor', false);
insert into bancos (id, nome, ativo) values (85	,'Cooperativa Central de Crédito - Ailos', false);
insert into bancos (id, nome, ativo) values (400	,'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE - CREDIT', false);
insert into bancos (id, nome, ativo) values (429	,'Crediare S.A. - Crédito, financiamento e investimento', false);
insert into bancos (id, nome, ativo) values (410	,'PLANNER SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (114	,'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP', false);
insert into bancos (id, nome, ativo) values (328	,'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE CALÇADOS DE SAPIRANGA', false);
insert into bancos (id, nome, ativo) values (36	,'Banco Bradesco BBI S.A.', false);
insert into bancos (id, nome, ativo) values (469	,'LIGA INVEST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (394	,'Banco Bradesco Financiamentos S.A.', false);
insert into bancos (id, nome, ativo) values (4	,'Banco do Nordeste do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (458	,'HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (320	,'China Construction Bank (Brasil) Banco Múltiplo S/A', false);
insert into bancos (id, nome, ativo) values (189	,'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS', false);
insert into bancos (id, nome, ativo) values (105	,'Lecca Crédito, Financiamento e Investimento S/A', false);
insert into bancos (id, nome, ativo) values (76	,'Banco KDB do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (82	,'BANCO TOPÁZIO S.A.', false);
insert into bancos (id, nome, ativo) values (312	,'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LT', false);
insert into bancos (id, nome, ativo) values (195	,'VALOR SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (93	,'PÓLOCRED   SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT', false);
insert into bancos (id, nome, ativo) values (391	,'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM', false);
insert into bancos (id, nome, ativo) values (273	,'Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel', false);
insert into bancos (id, nome, ativo) values (368	,'Banco CSF S.A.', false);
insert into bancos (id, nome, ativo) values (290	,'PAGSEGURO INTERNET INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (259	,'MONEYCORP BANCO DE CÂMBIO S.A.', false);
insert into bancos (id, nome, ativo) values (395	,'F.D''GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (364	,'EFÍ S.A. - INSTITUIÇÃO DE PAGAMENTO', false);
insert into bancos (id, nome, ativo) values (157	,'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.', false);
insert into bancos (id, nome, ativo) values (183	,'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P', false);
insert into bancos (id, nome, ativo) values (14	,'STATE STREET BRASIL S.A. - BANCO COMERCIAL', false);
insert into bancos (id, nome, ativo) values (130	,'CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (358	,'MIDWAY S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (127	,'Codepe Corretora de Valores e Câmbio S.A.', false);
insert into bancos (id, nome, ativo) values (79	,'PICPAY BANK - BANCO MÚLTIPLO S.A', false);
insert into bancos (id, nome, ativo) values (340	,'SUPERDIGITAL INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (81	,'BancoSeguro S.A.', false);
insert into bancos (id, nome, ativo) values (475	,'Banco Yamaha Motor do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (133	,'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E', false);
insert into bancos (id, nome, ativo) values (323	,'MERCADO PAGO INSTITUIÇÃO DE PAGAMENTO LTDA.', false);
insert into bancos (id, nome, ativo) values (121	,'Banco Agibank S.A.', false);
insert into bancos (id, nome, ativo) values (83	,'Banco da China Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (138	,'Get Money Corretora de Câmbio S.A.', false);
insert into bancos (id, nome, ativo) values (24	,'Banco Bandepe S.A.', false);
insert into bancos (id, nome, ativo) values (384	,'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO', false);
insert into bancos (id, nome, ativo) values (426	,'NEON FINANCEIRA - CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (88	,'BANCO RANDON S.A.', false);
insert into bancos (id, nome, ativo) values (319	,'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (274	,'BMP SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LTDA.', false);
insert into bancos (id, nome, ativo) values (95	,'Travelex Banco de Câmbio S.A.', false);
insert into bancos (id, nome, ativo) values (94	,'Banco Finaxis S.A.', false);
insert into bancos (id, nome, ativo) values (478	,'GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (276	,'BANCO SENFF S.A.', false);
insert into bancos (id, nome, ativo) values (447	,'MIRAE ASSET WEALTH MANAGEMENT (BRAZIL) CORRETORA DE CÂMBIO, TÍTULOS E VALORES MO', false);
insert into bancos (id, nome, ativo) values (47	,'Banco do Estado de Sergipe S.A.', false);
insert into bancos (id, nome, ativo) values (144	,'BEXS BANCO DE CÂMBIO S/A', false);
insert into bancos (id, nome, ativo) values (332	,'ACESSO SOLUÇÕES DE PAGAMENTO S.A. - INSTITUIÇÃO DE PAGAMENTO', false);
insert into bancos (id, nome, ativo) values (450	,'FITBANK INSTITUIÇÃO DE PAGAMENTOS ELETRÔNICOS S.A.', false);
insert into bancos (id, nome, ativo) values (126	,'BR Partners Banco de Investimento S.A.', false);
insert into bancos (id, nome, ativo) values (325	,'Órama Distribuidora de Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (301	,'DOCK INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (173	,'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (331	,'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (119	,'Banco Western Union do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (396	,'HUB INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (509	,'CELCOIN INSTITUICAO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (309	,'CAMBIONET CORRETORA DE CÂMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (254	,'PARANÁ BANCO S.A.', false);
insert into bancos (id, nome, ativo) values (268	,'BARI COMPANHIA HIPOTECÁRIA', false);
insert into bancos (id, nome, ativo) values (401	,'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (107	,'Banco Bocom BBM S.A.', false);
insert into bancos (id, nome, ativo) values (334	,'BANCO BESA S.A.', false);
insert into bancos (id, nome, ativo) values (412	,'SOCIAL BANK BANCO MÚLTIPLO S/A', false);
insert into bancos (id, nome, ativo) values (124	,'Banco Woori Bank do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (149	,'Facta Financeira S.A. - Crédito Financiamento e Investimento', false);
insert into bancos (id, nome, ativo) values (197	,'STONE INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (439	,'ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (313	,'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (142	,'Broker Brasil Corretora de Câmbio Ltda.', false);
insert into bancos (id, nome, ativo) values (529	,'PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (389	,'Banco Mercantil do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (184	,'Banco Itaú BBA S.A.', false);
insert into bancos (id, nome, ativo) values (634	,'BANCO TRIANGULO S.A.', false);
insert into bancos (id, nome, ativo) values (545	,'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A', false);
insert into bancos (id, nome, ativo) values (132	,'ICBC do Brasil Banco Múltiplo S.A.', false);
insert into bancos (id, nome, ativo) values (298	,'Vip''s Corretora de Câmbio Ltda.', false);
insert into bancos (id, nome, ativo) values (377	,'BMS SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (321	,'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT', false);
insert into bancos (id, nome, ativo) values (260	,'NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO', false);
insert into bancos (id, nome, ativo) values (470	,'CDC SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (129	,'UBS Brasil Banco de Investimento S.A.', false);
insert into bancos (id, nome, ativo) values (128	,'MS Bank S.A. Banco de Câmbio', false);
insert into bancos (id, nome, ativo) values (416	,'LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (461	,'ASAAS GESTÃO FINANCEIRA INSTITUIÇÃO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (194	,'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (536	,'NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO', false);
insert into bancos (id, nome, ativo) values (383	,'EBANX INSTITUICAO DE PAGAMENTOS LTDA.', false);
insert into bancos (id, nome, ativo) values (324	,'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (310	,'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (380	,'PICPAY INSTITUIçãO DE PAGAMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (163	,'Commerzbank Brasil S.A. - Banco Múltiplo', false);
insert into bancos (id, nome, ativo) values (280	,'WILL FINANCEIRA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (146	,'GUITTA CORRETORA DE CAMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (343	,'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.', false);
insert into bancos (id, nome, ativo) values (279	,'PRIMACREDI COOPERATIVA DE CRÉDITO DE PRIMAVERA DO LESTE', false);
insert into bancos (id, nome, ativo) values (335	,'Banco Digio S.A.', false);
insert into bancos (id, nome, ativo) values (349	,'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (427	,'COOPERATIVA DE CREDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPIRITO SANTO', false);
insert into bancos (id, nome, ativo) values (374	,'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (278	,'Genial Investimentos Corretora de Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (271	,'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (21	,'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO', false);
insert into bancos (id, nome, ativo) values (246	,'Banco ABC Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (292	,'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.', false);
insert into bancos (id, nome, ativo) values (751	,'Scotiabank Brasil S.A. Banco Múltiplo', false);
insert into bancos (id, nome, ativo) values (352	,'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (208	,'Banco BTG Pactual S.A.', false);
insert into bancos (id, nome, ativo) values (386	,'NU FINANCEIRA S.A. - Sociedade de Crédito, Financiamento e Investimento', false);
insert into bancos (id, nome, ativo) values (746	,'Banco Modal S.A.', false);
insert into bancos (id, nome, ativo) values (241	,'BANCO CLASSICO S.A.', false);
insert into bancos (id, nome, ativo) values (398	,'IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (336	,'Banco C6 S.A.', false);
insert into bancos (id, nome, ativo) values (612	,'Banco Guanabara S.A.', false);
insert into bancos (id, nome, ativo) values (604	,'Banco Industrial do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (505	,'Banco Credit Suisse (Brasil) S.A.', false);
insert into bancos (id, nome, ativo) values (329	,'QI Sociedade de Crédito Direto S.A.', false);
insert into bancos (id, nome, ativo) values (196	,'FAIR CORRETORA DE CAMBIO S.A.', false);
insert into bancos (id, nome, ativo) values (342	,'Creditas Sociedade de Crédito Direto S.A.', false);
insert into bancos (id, nome, ativo) values (300	,'Banco de la Nacion Argentina', false);
insert into bancos (id, nome, ativo) values (477	,'Citibank N.A.', false);
insert into bancos (id, nome, ativo) values (266	,'BANCO CEDULA S.A.', false);
insert into bancos (id, nome, ativo) values (122	,'Banco Bradesco BERJ S.A.', false);
insert into bancos (id, nome, ativo) values (376	,'BANCO J.P. MORGAN S.A.', false);
insert into bancos (id, nome, ativo) values (348	,'Banco XP S.A.', false);
insert into bancos (id, nome, ativo) values (473	,'Banco Caixa Geral - Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (745	,'Banco Citibank S.A.', false);
insert into bancos (id, nome, ativo) values (120	,'BANCO RODOBENS S.A.', false);
insert into bancos (id, nome, ativo) values (265	,'Banco Fator S.A.', false);
insert into bancos (id, nome, ativo) values (7	,'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL', false);
insert into bancos (id, nome, ativo) values (188	,'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES', false);
insert into bancos (id, nome, ativo) values (134	,'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (29	,'Banco Itaú Consignado S.A.', false);
insert into bancos (id, nome, ativo) values (467	,'MASTER S/A CORRETORA DE CâMBIO, TíTULOS E VALORES MOBILIáRIOS', false);
insert into bancos (id, nome, ativo) values (243	,'BANCO MASTER S/A', false);
insert into bancos (id, nome, ativo) values (397	,'LISTO SOCIEDADE DE CREDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (78	,'Haitong Banco de Investimento do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (525	,'INTERCAM CORRETORA DE CÂMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (355	,'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (367	,'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (528	,'REAG DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (445	,'PLANTAE S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (373	,'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.', false);
insert into bancos (id, nome, ativo) values (111	,'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.', false);
insert into bancos (id, nome, ativo) values (512	,'FINVEST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (516	,'FC FINANCEIRA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (408	,'BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (484	,'MAF DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (402	,'COBUCCIO S/A - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTOS', false);
insert into bancos (id, nome, ativo) values (507	,'SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO EFÍ S.A.', false);
insert into bancos (id, nome, ativo) values (404	,'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (418	,'ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A', false);
insert into bancos (id, nome, ativo) values (414	,'LEND SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (449	,'DM SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (518	,'MERCADO CRÉDITO SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.', false);
insert into bancos (id, nome, ativo) values (406	,'ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (403	,'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (419	,'NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (435	,'DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (455	,'FÊNIX DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (421	,'LAR COOPERATIVA DE CRÉDITO - LAR CREDI', false);
insert into bancos (id, nome, ativo) values (443	,'CREDIHOME SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (535	,'MARÚ SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (457	,'UY3 SOCIEDADE DE CRÉDITO DIRETO S/A', false);
insert into bancos (id, nome, ativo) values (428	,'CREDSYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (448	,'HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (452	,'CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (510	,'FFCRED SOCIEDADE DE CRÉDITO DIRETO S.A..', false);
insert into bancos (id, nome, ativo) values (462	,'STARK SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (465	,'CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (306	,'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (463	,'AZUMI DISTRIBUIDORA DE TíTULOS E VALORES MOBILIáRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (451	,'J17 - SOCIEDADE DE CRÉDITO DIRETO S/A', false);
insert into bancos (id, nome, ativo) values (444	,'TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (519	,'LIONS TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (454	,'MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (460	,'UNAVANTI SOCIEDADE DE CRÉDITO DIRETO S/A', false);
insert into bancos (id, nome, ativo) values (506	,'RJI CORRETORA DE TITULOS E VALORES MOBILIARIOS LTDA', false);
insert into bancos (id, nome, ativo) values (482	,'SBCASH SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (17	,'BNY Mellon Banco S.A.', false);
insert into bancos (id, nome, ativo) values (174	,'PEFISA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO', false);
insert into bancos (id, nome, ativo) values (481	,'SUPERLÓGICA SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (521	,'PEAK SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.', false);
insert into bancos (id, nome, ativo) values (433	,'BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (495	,'Banco de La Provincia de Buenos Aires', false);
insert into bancos (id, nome, ativo) values (523	,'HR DIGITAL - SOCIEDADE DE CRÉDITO DIRETO S/A', false);
insert into bancos (id, nome, ativo) values (527	,'ATICCA - SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (511	,'MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (513	,'ATF CREDIT SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (125	,'BANCO GENIAL S.A.', false);
insert into bancos (id, nome, ativo) values (537	,'MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE', false);
insert into bancos (id, nome, ativo) values (524	,'WNT CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (526	,'MONETARIE SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (488	,'JPMorgan Chase Bank, National Association', false);
insert into bancos (id, nome, ativo) values (530	,'SER FINANCE SOCIEDADE DE CRÉDITO DIRETO S.A.', false);
insert into bancos (id, nome, ativo) values (65	,'Banco AndBank (Brasil) S.A.', false);
insert into bancos (id, nome, ativo) values (145	,'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.', false);
insert into bancos (id, nome, ativo) values (250	,'BCV - BANCO DE CRÉDITO E VAREJO S.A.', false);
insert into bancos (id, nome, ativo) values (253	,'Bexs Corretora de Câmbio S/A', false);
insert into bancos (id, nome, ativo) values (269	,'BANCO HSBC S.A.', false);
insert into bancos (id, nome, ativo) values (213	,'Banco Arbi S.A.', false);
insert into bancos (id, nome, ativo) values (139	,'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo', false);
insert into bancos (id, nome, ativo) values (18	,'Banco Tricury S.A.', false);
insert into bancos (id, nome, ativo) values (422	,'Banco Safra S.A.', false);
insert into bancos (id, nome, ativo) values (630	,'BANCO LETSBANK S.A.', false);
insert into bancos (id, nome, ativo) values (224	,'Banco Fibra S.A.', false);
insert into bancos (id, nome, ativo) values (393	,'Banco Volkswagen S.A.', false);
insert into bancos (id, nome, ativo) values (600	,'Banco Luso Brasileiro S.A.', false);
insert into bancos (id, nome, ativo) values (390	,'BANCO GM S.A.', false);
insert into bancos (id, nome, ativo) values (623	,'Banco Pan S.A.', false);
insert into bancos (id, nome, ativo) values (655	,'Banco Votorantim S.A.', false);
insert into bancos (id, nome, ativo) values (479	,'Banco ItauBank S.A.', false);
insert into bancos (id, nome, ativo) values (456	,'Banco MUFG Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (464	,'Banco Sumitomo Mitsui Brasileiro S.A.', false);
insert into bancos (id, nome, ativo) values (237	,'Banco Bradesco S.A.', false);
insert into bancos (id, nome, ativo) values (381	,'BANCO MERCEDES-BENZ DO BRASIL S.A.', false);
insert into bancos (id, nome, ativo) values (613	,'Omni Banco S.A.', false);
insert into bancos (id, nome, ativo) values (637	,'BANCO SOFISA S.A.', false);
insert into bancos (id, nome, ativo) values (653	,'BANCO VOITER S.A.', false);
insert into bancos (id, nome, ativo) values (69	,'Banco Crefisa S.A.', false);
insert into bancos (id, nome, ativo) values (370	,'Banco Mizuho do Brasil S.A.', false);
insert into bancos (id, nome, ativo) values (249	,'Banco Investcred Unibanco S.A.', false);
insert into bancos (id, nome, ativo) values (318	,'Banco BMG S.A.', false);
insert into bancos (id, nome, ativo) values (626	,'BANCO C6 CONSIGNADO S.A.', false);
insert into bancos (id, nome, ativo) values (508	,'AVENUE SECURITIES DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (270	,'SAGITUR CORRETORA DE CÂMBIO S.A.', false);
insert into bancos (id, nome, ativo) values (366	,'BANCO SOCIETE GENERALE BRASIL S.A.', false);
insert into bancos (id, nome, ativo) values (113	,'NEON CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (131	,'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA', false);
insert into bancos (id, nome, ativo) values (11	,'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A', false);
insert into bancos (id, nome, ativo) values (611	,'Banco Paulista S.A.', false);
insert into bancos (id, nome, ativo) values (755	,'Bank of America Merrill Lynch Banco Múltiplo S.A.', false);
insert into bancos (id, nome, ativo) values (89	,'CREDISAN COOPERATIVA DE CRÉDITO', false);
insert into bancos (id, nome, ativo) values (643	,'Banco Pine S.A.', false);
insert into bancos (id, nome, ativo) values (140	,'NU INVEST CORRETORA DE VALORES S.A.', false);
insert into bancos (id, nome, ativo) values (707	,'Banco Daycoval S.A.', false);
insert into bancos (id, nome, ativo) values (288	,'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (363	,'SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.', false);
insert into bancos (id, nome, ativo) values (101	,'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (487	,'DEUTSCHE BANK S.A. - BANCO ALEMAO', false);
insert into bancos (id, nome, ativo) values (233	,'Banco Cifra S.A.', false);
insert into bancos (id, nome, ativo) values (177	,'Guide Investimentos S.A. Corretora de Valores', false);
insert into bancos (id, nome, ativo) values (438	,'TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.', false);
insert into bancos (id, nome, ativo) values (365	,'SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS  S.A.', false);
insert into bancos (id, nome, ativo) values (633	,'Banco Rendimento S.A.', false);
insert into bancos (id, nome, ativo) values (218	,'Banco BS2 S.A.', false);
insert into bancos (id, nome, ativo) values (293	,'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.', false);
insert into bancos (id, nome, ativo) values (285	,'Frente Corretora de Câmbio Ltda.', false);
insert into bancos (id, nome, ativo) values (80	,'B&T CORRETORA DE CAMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (753	,'Novo Banco Continental S.A. - Banco Múltiplo', false);
insert into bancos (id, nome, ativo) values (222	,'BANCO CRÉDIT AGRICOLE BRASIL S.A.', false);
insert into bancos (id, nome, ativo) values (281	,'Cooperativa de Crédito Rural Coopavel', false);
insert into bancos (id, nome, ativo) values (754	,'Banco Sistema S.A.', false);
insert into bancos (id, nome, ativo) values (311	,'DOURADA CORRETORA DE CÂMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (98	,'Credialiança Cooperativa de Crédito Rural', false);
insert into bancos (id, nome, ativo) values (610	,'Banco VR S.A.', false);
insert into bancos (id, nome, ativo) values (712	,'Banco Ourinvest S.A.', false);
insert into bancos (id, nome, ativo) values (720	,'BANCO RNX S.A.', false);
insert into bancos (id, nome, ativo) values (10	,'CREDICOAMO CREDITO RURAL COOPERATIVA', false);
insert into bancos (id, nome, ativo) values (440	,'CREDIBRF - COOPERATIVA DE CRÉDITO', false);
insert into bancos (id, nome, ativo) values (442	,'MAGNETIS - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', false);
insert into bancos (id, nome, ativo) values (283	,'RB INVESTIMENTOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LIMITADA', false);
insert into bancos (id, nome, ativo) values (33	,'BANCO SANTANDER (BRASIL) S.A.', false);
insert into bancos (id, nome, ativo) values (217	,'Banco John Deere S.A.', false);
insert into bancos (id, nome, ativo) values (41	,'Banco do Estado do Rio Grande do Sul S.A.', false);
insert into bancos (id, nome, ativo) values (117	,'ADVANCED CORRETORA DE CÂMBIO LTDA', false);
insert into bancos (id, nome, ativo) values (654	,'BANCO DIGIMAIS S.A.', false);
insert into bancos (id, nome, ativo) values (371	,'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.', false);
insert into bancos (id, nome, ativo) values (212	,'Banco Original S.A.', false);
insert into bancos (id, nome, ativo) values (289	,'EFX CORRETORA DE CÂMBIO LTDA.', false);
