CREATE TABLE if not exists contas_nao_credenciadas (
	id SERIAL PRIMARY KEY,
	banco_id INT,
	codage INT,
	codcta INT,
	codctabco INT,
	convenio INT,
	carteira INT,
	variacao INT,
	modalidade INT,
	ultnumbol VARCHAR,
	statusapi VARCHAR(100),
	idparceiro INT,
	registrobase INT,
	dh_created_at TIMESTAMP,
	dh_updated_at TIMESTAMP,
	clientid VARCHAR,
	clientsecret VARCHAR,
	dh_desativacao TIMESTAMP,
	indicador_pix VARCHAR(100),
	descricao VARCHAR(40),
	codigo_empresa INT,
	emite_boleto VARCHAR(1) NOT NULL DEFAULT 'S',
	ativa VARCHAR(1) NOT NULL DEFAULT 'S',
	tipo_api_boleto VARCHAR(1),
	data_registro_conta TIMESTAMP,
	api_baixa_automatica VARCHAR(1),
	api_conciliacao_automatica VARCHAR(1),
	aceita_titulo_vencido VARCHAR(32),
	recebimento_parcial VARCHAR(32),
	recebimento_dias INT,
	orgao_negativador INT,
	quantidade_dias_protesto INT,
	quantidade_dias_negativacao INT,
	instrucao_protesto INT,
	instrucao_negativacao INT,
	contabilizar_dias bool NOT NULL DEFAULT TRUE,
	tipo_juros_mora VARCHAR(1),
	valor_juros_mora FLOAT,
	tipo_multa VARCHAR(1),
	tipo_data_multa VARCHAR(1),
	quantidade_dias_multa INT,
	valor_multa FLOAT,
	CONSTRAINT contas_n_cred_id_fkey FOREIGN KEY (banco_id) REFERENCES public.bancos(id),
	CONSTRAINT contas_n_cred_idparceiro_fkey FOREIGN KEY (idparceiro) REFERENCES public.parceiros(id)
);
